#include <string>

typedef std::string StringName;

class Nameable{
	public:
		StringName getName();
		void setName(StringName);
		void setName();

	private:
		static int lastAutoGenerated;
		StringName name;
};
