#include <string>

#ifndef NAMEABLE_H
#define NAMEABLE_H

typedef std::string StringName;

class Nameable{
	public:
		StringName getName();
		void setName(StringName);
		void setName();

	protected:
		static int lastAutoGenerated;
		StringName name;
};

#endif // NAMEABLE_H
