#include "core/Object.h"

int Object::lastAutoGeneratedName = 0;

Object::Object(){
	setName();
}

Object::Object(std::string newName){
	setName(newName);
}

std::string Object::getName(){
	return name;
}

void Object::setName(std::string name){
	this->name = name;
}

void Object::setName(){
    setName("Object_" + std::to_string(++Object::lastAutoGeneratedName));
}

const char * Object::print(std::string message, bool print){
	message = "[" + name + "]: " + message;
	if(print){
		std::cout << message << std::endl;
	}
	return message.c_str();
}